sabzweb/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    # path('posts/<int:id>', views.post_detail, name="post_detail"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login/', views.login,name="login"),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout/', views.log_out, name="logout"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('register/', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
]

sabzweb/sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sabzweb/blog/forms.py
from cProfile import label

from django import forms
from .models import Comment, Post, User, Account
from django.contrib.auth.forms import AuthenticationForm

class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'متن',
                'class':'form-control'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'نام',
                'class': 'form-control'
            }),
        }

class SearchForm(forms.Form):
    query = forms.CharField()

class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets={
            'title': forms.TextInput(attrs={
                'class':'form-control',
                'id' : "con-name",

            }),
            'description': forms.Textarea(attrs={
            	'class': 'form-control',
				 'rows': '5',
            }),
            'reading_time': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'category': forms.Select(attrs={
                'class': 'form-select',
            }),


        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name' , 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '5',
            }),
            'job': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-control',
            }),
        }

sabzweb/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.contrib.auth.decorators import login_required

def index(request):
    last_post = Post.published.all().order_by('-publish')[0]
    return render(request, "blog/index.html", {"last_post": last_post})


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    print(posts, type(posts))
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog/list.html", context)

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 4
    template_name = "blog/list.html"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


def post_search(request):
    query=None
    results=[]
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results1=Post.published.annotate(similarity=TrigramSimilarity('title', query))\
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
    context={
        'query':query,
        'results':results
    }
    return render(request,'blog/search.html',context)

@login_required
def profile(request):
    user = request.user
    posts= Post.published.filter(author=user)

    return render(request, 'blog/profile.html', {'posts':posts})

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post= post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete-post.html', {'post': post})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create-post.html', {'form': form, 'post': post})

# def user_login(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('Your account is disabled')
#             else:
#                 return HttpResponse('You are not logged in')
#
#     else:
#         form = LoginForm()
#     return render(request, 'forms/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return  render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context ={
        'account_form': account_form,
        'user_form': user_form
    }
    return render(request, 'registration/edit_account.html', context)

sabzweb/blog/templates/partials/footer.html
{% load static %}
<footer class="pb-0">
	<div class="container">
		<hr>
		<!-- Widgets START -->
		<div class="row pt-5">
			<!-- Footer Widget -->
			<div class="col-md-6 col-lg-4 mb-4">
				<img class="light-mode-item" style="width: 120px; height: 60px" src="{% static 'images/icon/blog-logo.png' %}" alt="logo">
				<img class="dark-mode-item" style="width: 120px; height: 60px" src="{% static 'images/icon/blog-logo.png' %}" alt="logo">
				<p class="mt-3">این وبسیات یک وبسایت تمرینی برای دوره متخصص جنگو سبزلرن است</p>
				<div class="mt-4">©2022 ارائه شده توسط سبزلرن
				</div>
			</div>

			<!-- Footer Widget -->
			<div class="col-md-6 col-lg-3 mb-4">
				<h5 class="mb-4">لینک های مفید</h5>
				<div class="row">
					<div class="col-6">
						<ul class="nav flex-column">
							<li class="nav-item"><a class="nav-link pt-0" href="{% url 'blog:post_list' %}">لیست پست ها</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:profile' %}">داشبورد</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:ticket' %}">ارسال تیکت</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:create_post' %}">ایجاد پست</a></li>
						</ul>
					</div>
 					<div class="col-6">
						<ul class="nav flex-column">
							<li class="nav-item"><a class="nav-link pt-0" href="{% url 'blog:post_list_category' 'تکنولوژِی' %}">تکنولوژِی</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}">هوش مصنوعی</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list_category' 'زبان برنامه نویسی' %}">زبان برنامه نویسی</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list_category' 'بلاکچین' %}">بلاکچین</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'blog:post_list_category' 'سایر' %}">سایر</a></li>
						</ul>
					</div>
				</div>
			</div>

			<!-- Footer Widget -->
			<div class="col-sm-6 col-lg-3 mb-4">
				<h5 class="mb-4">پربیننده ترین</h5>
				<ul class="list-inline">
					<li class="list-inline-item"><a href="{% url 'blog:post_list_category' 'تکنولوژِی' %}" class="btn btn-sm btn-primary-soft">تکنولوژِی</a></li>
					<li class="list-inline-item"><a href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}" class="btn btn-sm btn-success-soft">هوش مصنوعی</a></li>
					<li class="list-inline-item"><a href="{% url 'blog:post_list_category' 'زبان برنامه نویسی' %}#" class="btn btn-sm btn-warning-soft">زبان برنامه نویسی</a></li>
					<li class="list-inline-item"><a href="{% url 'blog:post_list_category' 'بلاکچین' %}" class="btn btn-sm btn-danger-soft">بلاکچین</a></li>
					<li class="list-inline-item"><a href="{% url 'blog:post_list_category' 'سایر' %}" class="btn btn-sm btn-info-soft">سایر</a></li>
				</ul>
			</div>

			<!-- Footer Widget -->
			<div class="col-sm-6 col-lg-2 mb-4">
				<h5 class="mb-4">شبکه های اجتماعی</h5>
				<ul class="nav flex-column">
					<li class="nav-item"><a class="nav-link pt-0" href="#"><i class="fab fa-facebook-square fa-fw me-2 text-facebook"></i>Facebook</a></li>
					<li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-twitter-square fa-fw me-2 text-twitter"></i>Twitter</a></li>
					<li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-linkedin fa-fw me-2 text-linkedin"></i>Linkedin</a></li>
					<li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-youtube-square fa-fw me-2 text-youtube"></i>YouTube</a></li>
				</ul>
			</div>
		</div>
		<!-- Widgets END -->
	</div>
</footer>

sabzweb/blog/templates/partials/header.html
{% load static %}

<header class="navbar-light navbar-sticky header-static">
	<!-- Logo Nav START -->
	<nav class="navbar navbar-expand-lg">
		<div class="container">
			<!-- Logo START -->
			<a class="navbar-brand" href="{% url 'blog:index' %}">
				<img class="navbar-brand-item light-mode-item" style="width: 120px; height: 60px" src="{% static 'images/icon/blog-logo.png' %}" alt="logo">
				<img class="navbar-brand-item dark-mode-item" style="width: 160px; height: 80px" src="{% static 'images/icon/blog-logo.png' %}" alt="logo">
			</a>
			<!-- Logo END -->

			<!-- Nav right START -->
			<div class="nav ms-sm-3 flex-nowrap align-items-center">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="homeMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">صفحات</a>
                    <ul class="dropdown-menu" aria-labelledby="homeMenu">
                        <li> <a class="dropdown-item" href="{% url 'blog:index' %}">صفحه اصلی</a></li>
                        <li> <a class="dropdown-item" href="{% url 'blog:profile' %}">داشبورد</a></li>
                        <li> <a class="dropdown-item" href="{% url 'blog:post_list' %}">لیست مقالات</a></li>
                    </ul>
                </li>
            </ul>

				<!-- Dark mode options START -->
					<div class="nav-item dropdown ms-3">
						<!-- Switch button -->
						<button class="modeswitch" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
							<svg class="theme-icon-active"><use href="#"></use></svg>
						</button>
						<!-- Dropdown items -->
						<ul class="dropdown-menu min-w-auto dropdown-menu-end" aria-labelledby="bd-theme">
							<li class="mb-1">
								<button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light">
									<svg width="16" height="16" fill="currentColor" class="bi bi-brightness-high-fill fa-fw mode-switch me-1" viewBox="0 0 16 16">
										<path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
										<use href="#"></use>
									</svg>روشن
								</button>
							</li>
							<li class="mb-1">
								<button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-stars-fill fa-fw mode-switch me-1" viewBox="0 0 16 16">
										<path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
										<path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
										<use href="#"></use>
									</svg>تیره
								</button>
							</li>
							<li>
								<button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-half fa-fw mode-switch me-1" viewBox="0 0 16 16">
										<path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
										<use href="#"></use>
									</svg>خودکار
								</button>
							</li>
						</ul>
					</div>

					<!-- Dark mode options END -->
				{% if request.user.is_authenticated %}
				<div class="nav-item d-none d-md-block">
					<a href="{% url 'blog:profile' %}" class="btn btn-sm btn-danger mb-0 mx-2">{{request.user.first_name|default:request.user.username }}</a>
				</div>
                {% else %}
                    <a href="{% url 'blog:login' %}" class="btn btn-sm btn-danger mb-0 mx-2">ورود</a>
                     <a href="{% url 'blog:register' %}" class="btn btn-sm btn-outline-info mb-0 mx-2">ثبت نام</a>
				{% endif %}

				<!-- Nav Search -->
				<div class="nav-item dropdown nav-search dropdown-toggle-icon-none">
					<a class="nav-link pe-0 dropdown-toggle" role="button" href="#" id="navSearch" data-bs-toggle="dropdown" aria-expanded="false">
						<i class="bi bi-search fs-4"> </i>
					</a>
					<div class="dropdown-menu dropdown-menu-end shadow rounded p-2" aria-labelledby="navSearch">
					  <form class="input-group" method="get" action="{% url 'blog:post_search' %}">
                            <input class="form-control border-success" name="query" type="search" placeholder="جستجو" aria-label="Search">
                            <button class="btn btn-success m-0" type="submit">جستجو</button>
					  	</form>
					</div>
				</div>
			</div>
			<!-- Nav right END -->
		</div>
	</nav>
	<!-- Logo Nav END -->
</header>

sabzweb/blog/templates/partials/latest_posts.html
{% load static %}
{% load blog_tags %}
{% load jformat %}

{% for post in l_posts %}
    <div class="col-sm-6 col-lg-4">
    <!-- Card item START -->
    <div class="card">
    <!-- Card img -->
    <div class="position-relative">
    <img class="card-img rounded-0" src="{{ post.images.first.image_file.url }}" alt="Card image">
    <div class="card-img-overlay d-flex align-items-start flex-column p-3">
      <!-- Card overlay bottom -->
      <div class="w-100 mt-auto">
        <a href="#" class="badge text-bg-dark mb-2">{{ post.category}}</a>
      </div>
    </div>
    </div>
    <div class="card-body px-0 pt-3">
    <h4 class="card-title"><a href="{{ post.get_absolute_url }}" class="btn-link text-reset stretched-link">{{ post.title }}</a></h4>
    <!-- Card info -->
    <p>{{ post.description | markdown | truncatewords:50 }}</p>
    <!-- Card info -->
    <ul class="nav nav-divider align-items-center">
      <li class="nav-item">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</li>
    </ul>
    </div>
    </div>
    </div>
{% endfor %}

sabzweb/blog/templates/partials/pagination.html
<nav class="my-5" aria-label="navigation">
    <ul class="pagination d-inline-block d-md-flex justify-content-center">

{% if page.has_previous %}
    <li class="page-item">
    	<a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1" aria-disabled="true">قبل</a>
    </li>

  {% if page.number > 3 %}
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% if page.number > 4 %}
      <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
    {% endif %}
  {% endif %}

{% endif %}

{% for num in page.paginator.page_range %}
  {% if page.number == num %}
    <li class="page-item"><a class="page-link active" href="?page={{ num }}">{{ num }}</a></li>
  {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
  {% endif %}
{% endfor %}

{% if page.has_next %}
  {% if page.number < page.paginator.num_pages|add:'-3' %}
    <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
  {% elif page.number < page.paginator.num_pages|add:'-2' %}
      <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>

  {% endif %}
    <li class="page-item">
    	<a class="page-link" href="?page={{ page.next_page_number }}">بعد</a>
    </li>
{% endif %}

	</ul>
</nav>