sabzshop/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'api'


router = DefaultRouter()
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    # path('products/', views.ProductListAPIView.as_view(), name='products_list_api'),
    # path('product/<pk>/', views.ProductDetailAPIView.as_view(), name='product_detail_api'),
    path('users/', views.UserListAPIView.as_view(), name='users_list_api'),
    path('register/', views.UserRegistrationAPIView.as_view(), name='register_api'),
    path('', include(router.urls)),
    path('orders/', views.OrderListAPIView.as_view(), name='orders_list_api'),
    path('orders/<int:pk>/', views.OrderDetailAPIView.as_view(), name='order_detail_api'),
]

sabzshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('verify-code/', views.verify_code, name='verify_code'),
    path('order-create/', views.order_create, name='order_create'),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('orders-list/', views.orders_list, name='orders-list'),
    path('order-detail/<int:id>', views.order_detail, name='order-detail'),

]

sabzshop/sabzshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sabzshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

sabzshop/orders/models.py
from django.db import models
from shop.models import Product
from account.models import ShopUser


# Create your models here.

class Order(models.Model):
    buyer = models.ForeignKey(ShopUser, related_name='orders', on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=10)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش ها'

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_post_cost(self):
        weight = sum(item.get_weight() for item in self.items.all())
        if weight < 1000:
            return 0
        elif 1000 <= weight <= 2000:
            return 0
        else:
            return 0

    def get_final_cost(self):
        price = self.get_post_cost() + self.get_total_cost()
        return price


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    weight = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'آیتم سفارش'
        verbose_name_plural = 'آیتم های سفارش'
    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def get_weight(self):
        return self.weight * self.quantity

sabzshop/orders/forms.py
from django import forms
from .models import Order


class PhoneVerificationForm(forms.Form):
    phone = forms.CharField(max_length=11, label='شماره تلفن')


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'address',
                  'postal_code', 'province', 'city']

sabzshop/orders/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import PhoneVerificationForm, OrderCreateForm
from account.models import ShopUser
from .models import OrderItem, Order
from cart.cart import Cart
import random
from cart.common.KaveSms import send_sms_with_template
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import redirect
from django.http import HttpResponse
import requests
import json


def verify_phone(request):
    if request.user.is_authenticated:
        return redirect('orders:order_create')
    if request.method == 'POST':
        form = PhoneVerificationForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            if ShopUser.objects.filter(phone=phone).exists():
                messages.error(request, 'this phone is already registered.')
                return redirect('orders:verify_phone')
            else:
                tokens = {'token': ''.join(random.choices('0123456789', k=6))}
                request.session['verification_code'] = tokens['token']
                request.session['phone'] = phone
                print(tokens)
                # send_sms_with_template(phone, tokens, 'verify')
                messages.error(request, 'verification code sent successfully.')
                return redirect('orders:verify_code')
    else:
        form = PhoneVerificationForm()
    return render(request, 'verify_phone.html', {'form': form})


def verify_code(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        if code:
            verification_code = request.session['verification_code']
            phone = request.session['phone']
            if code == verification_code:
                user = ShopUser.objects.create_user(phone=phone)
                user.set_password('123456')
                user.save()
                # send sms
                print(user)
                login(request, user)
                del request.session['verification_code']
                del request.session['phone']
                return redirect('orders:order_create')
            else:
                messages.error(request, 'Verification code is incorrect.')
    return render(request, 'verify_code.html')


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.buyer = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['price'], quantity=item['quantity'],
                                         weight=item['weight'])
            cart.clear()
            request.session['order_id'] = order.id
            return redirect('orders:request')
    else:
        form = OrderCreateForm()
    return render(request, 'order_create.html', {'form': form, 'cart': cart})


# ? sandbox merchant
if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"

CallbackURL = 'http://127.0.0.1:8000/order/verify/'


def send_request(request):
    order = Order.objects.get(id=request.session['order_id'])
    description = ""
    for item in order.items.all():
        description += item.product.name + ", "
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Description": description,
        "Phone": request.user.phone,
        "CallbackURL": CallbackURL,
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

        if response.status_code == 200:
            response_json = response.json()
            authority = response_json['Authority']
            if response_json['Status'] == 100:
                return redirect(ZP_API_STARTPAY + authority)
            else:
                return HttpResponse('Error')
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def verify(request):
    order = Order.objects.get(id=request.session['order_id'])
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Authority": request.GET.get('Authority'),
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_VERIFY, data=data, headers=headers)
        if response.status_code == 200:
            response_json = response.json()
            reference_id = response_json['RefID']

            if response_json['Status'] == 100:
                for item in order.items.all():
                    item.product.inventory -= item.quantity
                    item.product.save()
                order.paid = True
                order.save()
                return render(request, 'payment-tracking.html',
                              {"success": True, 'RefID': reference_id, "order_id": order.id})
            else:
                return render(request, 'payment-tracking.html',
                              {"success": False, })
        del request.session['order_id']
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def orders_list(request):
    try:
        user = request.user
        orders = Order.objects.filter(buyer=user)
        return render(request, 'orders-list.html', {'orders': orders})
    except:
        return render(request, 'orders-list.html', )


def order_detail(request, id):
    order = Order.objects.get(id=id)
    context = {
        'order': order,
    }
    return render(request, 'order-detail.html', context)

sabzshop/orders/templates/order-detail.html
<!DOCTYPE html>
<html dir="rtl" lang="fa">
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}جزئیات سفارش{% endblock %}

{% block content %}
		<div class="body">

			<div role="main" class="main">

				<section class="page-header page-header-modern page-header-background page-header-background-sm overlay overlay-color-primary overlay-show overlay-op-8 mb-5" style="background-image: url(img/page-header/page-header-elements.jpg);">
					<div class="container">
						<div class="row">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="mb-n2">جزئیات تراکنش</h1>
							</div>
							<div class="col-md-12 align-self-center order-1">
								<ul class="breadcrumb breadcrumb-light d-block text-center">

								</ul>
							</div>
						</div>
					</div>
				</section>
                 <div class="img-fluid mx-5">
                 {% for item in order.items.all %}
                    {% for product in item.product.images.all %}
                        <a class="d-inline-block" href="{{ order.items.first.product.get_absolute_url }}"><img src="{{ product.file.url }}" width="400" height="420" alt="product picture"></a>
                    {% endfor %}
                 {% endfor %}
{#                    <a class="d-inline-block" href="{{ order.items.first.product.get_absolute_url }}"><img src="{{ order.items.first.product.images.first.file.url }}" width="400" height="420" alt="product picture"></a>#}

                    <div class="d-inline-block mx-5">
                        <ul class="list list-icons">
                            {% for item in order.items.all %}
                            <li><i class="fas fa-check"></i>نام محصول:  {{ item.product.name }}</li>
                            <li><i class="fas fa-arrow-alt-circle-left"></i>تعداد:  {{ item.quantity }}</li>
                            <li><i class="fas fa-money-bill-wave"></i>قیمت:  {{ item.price }}</li>
                            {% endfor %}
                            <li><i class="fa fa-history"></i>تاریخ ایجاد:  {{ order.created }}</li>
                            <li><i class="fa fa-list"></i>استان:  {{ order.province }}</li>
                            <li><i class="fa fa-city"></i>شهر:  {{ order.city }}</li>
                            <li><i class="far fa-address-card"></i>آدرس:  {{ order.address }}</li>
                        {% if order.paid %}
                            <li><i class="far fa-address-card"></i>وضعیت:  <i class="fa fa-check text-success"></i></li>
                        {% else %}
                            <li><i class="fa fa-key"></i>وضعیت:  <i class="fa fa-stop-circle text-danger"></i></li>
                        {% endif %}
                        </ul>
                    </div>
                </div>



				<div class="container py-2">

					<div class="row">
						<div class="col">


						</div>
					</div>

				</div>

			</div>
 
		</div>

{% endblock %}
</html>

sabzshop/orders/templates/order_create.html
<!DOCTYPE html>
<html dir="rtl" lang="fa">
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}ایجاد سفارش{% endblock %}

{% block content %}
		<div class="body">

			<div role="main" class="main shop py-4">

				<div class="container">

					<div class="row">
						<div class="col-lg-9">
                            <form id="frmBillingAddress" method="post">
                            {% csrf_token %}
							<div class="accordion accordion-modern" id="accordion">
								<div class="card card-default">
									<div class="card-header">
										<h4 class="card-title m-0">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
												آدرس صورت حساب
											</a>
										</h4>
									</div>
									<div id="collapseOne" class="collapse show">
										<div class="card-body">
												<div class="form-row">
													<div class="form-group col-lg-6">
														<label class="font-weight-bold text-dark text-2" for="id_first_name">نام</label>
														<input type="text" name="first_name" class="form-control" id="id_first_name">
													</div>
													<div class="form-group col-lg-6">
														<label class="font-weight-bold text-dark text-2" for="id_last_name">نام خانوادگی</label>
														<input type="text" name="last_name" class="form-control" id="id_last_name">
													</div>
												</div>
												<div class="form-row">
													<div class="form-group col">
														<label class="font-weight-bold text-dark text-2" for="id_phone">شماره تلفن</label>
														<input type="text" name="phone" class="form-control" id="id_phone">
													</div>
                                                    <div class="form-group col">
														<label class="font-weight-bold text-dark text-2" for="id_postal_code">کدپستی</label>
														<input type="text" name="postal_code" class="form-control" id="id_postal_code">
													</div>
												</div>
												<div class="form-row">
													<div class="form-group col">
														<label class="font-weight-bold text-dark text-2" for="id_province">استان </label>
														<input type="text" name="province" class="form-control" id="id_province">
													</div>
                                                    <div class="form-group col">
														<label class="font-weight-bold text-dark text-2" for="id_city">شهر </label>
														<input type="text" name="city" class="form-control" id="id_city">
													</div>
												</div>
                                                <div class="form-row">
                                                    <div class="form-group col">
														<label class="font-weight-bold text-dark text-2" for="id_address">آدرس </label>
														<input type="text" name="address" class="form-control" id="id_address">
													</div>
												</div>

												<div class="form-row">
{#													<div class="form-group col">#}
{#														<input type="submit" value="ادامه" class="btn btn-xl btn-light pr-4 pl-4 text-2 font-weight-semibold text-uppercase float-right mb-2" data-loading-text="در حال بارگذاری ...">#}
{#													</div>#}
												</div>

										</div>
									</div>
								</div>
								<div class="card card-default">
{#									<div class="card-header">#}
{#										<h4 class="card-title m-0">#}
{#											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">#}
{#												آدرس ارسال#}
{#											</a>#}
{#										</h4>#}
{#									</div>#}
									<div id="collapseTwo" class="collapse">
									</div>
								</div>
								<div class="card card-default">
									<div class="card-header">
										<h4 class="card-title m-0">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
												بررسی و پرداخت
											</a>
										</h4>
									</div>
									<div id="collapseThree" class="collapse">
										<div class="card-body">
											<table class="shop_table cart">
												<thead>
													<tr>
														<th class="product-thumbnail">
															
														</th>
														<th class="product-name">
															محصول
														</th>
														<th class="product-price">
															قیمت
														</th>
														<th class="product-quantity">
															تعداد
														</th>
														<th class="product-subtotal">
															جمع
														</th>
													</tr>
												</thead>
												<tbody>
                                                {% for item in cart %}
													<tr class="cart_table_item">
														<td class="product-thumbnail">
															<a href="{{ item.product.get_absolute_url }}">
																<img width="100" height="100" alt="" class="img-fluid" src="{{ item.product.images.first.file.url }}">
															</a>
														</td>
														<td class="product-name">
															<a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a>
														</td>
														<td class="product-price">
															<span class="amount">{{ item.product.price }} تومان</span>
														</td>
														<td class="product-quantity">
															{{ item.quantity }}
														</td>
														<td class="product-subtotal">
															<span class="amount">{{ item.total }} تومان</span>
														</td>
													</tr>
                                                {% endfor %}
												</tbody>
											</table>
							
											<hr class="solid my-5">
							
											<h4 class="text-primary">مجموع سبد</h4>
											<table class="cart-totals">
												<tbody>
													<tr class="cart-subtotal">
														<th>
															<strong class="text-dark">جمع سبد</strong>
														</th>
														<td>
															<strong class="text-dark"><span class="amount">{{ cart.get_total_price }} تومان</span></strong>
														</td>
													</tr>
													<tr class="shipping">
														<th>
															حمل و نقل
														</th>
														<td>
															ارسال رایگان<input type="hidden" value="free_shipping" id="shipping_method" name="shipping_method">
														</td>
													</tr>
													<tr class="total">
														<th>
															<strong class="text-dark d-inline-block pt-1">مجموع سفارش</strong>
														</th>
														<td>
															<strong><span class="amount pt-1">{{ cart.get_final_price }} <small>تومان</small></span></strong>
														</td>
													</tr>
												</tbody>
											</table>
							
											<hr class="solid my-5">
							
											<h4 class="text-primary">پرداخت</h4>

										</div>
									</div>
								</div>
							</div>

							
							<div class="actions-continue mt-2">
                                <button type="submit" class="btn btn-primary btn-modern text-uppercase mt-4 mb-5 mb-lg-0">ثبت سفارش</button>
							</div>
                            </form>

						</div>
						<div class="col-lg-3 mt-3 mt-lg-0 mb-n3">
							<h4 class="text-primary">مجموع سبد</h4>
							<table class="cart-totals">
								<tbody>
									<tr class="cart-subtotal">
										<th>
											<strong class="text-dark">جمع سبد</strong>
										</th>
										<td>
											<strong class="text-dark"><span class="amount">{{ cart.get_total_price }} تومان</span></strong>
										</td>
									</tr>
									<tr class="shipping">
										<th>
											حمل و نقل
										</th>
										<td>
											ارسال رایگان<input type="hidden" value="free_shipping" id="shipping_method2" name="shipping_method">
										</td>
									</tr>
									<tr class="total">
										<th>
											<strong class="text-dark d-inline-block pt-1">مجموع سفارش</strong>
										</th>
										<td>
											<strong><span class="amount pt-1"><span class="text-1">{{ cart.get_final_price }}</span> <small>تومان</small></span></strong>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
		</div>
{% endblock %}
</html>

sabzshop/orders/templates/orders-list.html
<!DOCTYPE html>
<html dir="rtl" lang="fa">
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}لیست سفارش ها{% endblock %}

{% block content %}

		<div class="body">

			<div role="main" class="main">

				<div class="container py-2">

					<div class="row">
						<div class="col">
							<div class="row">
								<div class="col pb-3">
									<h4>تراکنش ها من</h4>

									<table class="table">
										<thead>
											<tr>
                                                <th>

                                                </th>
												<th>
                                                    تاریخ سفارش
												</th>
												<th>
                                                    نام محصول
												</th>
												<th>
                                                    قیمت
                                                </th>
                                                <th>
                                                    تعداد
                                                </th>
                                                <th>
                                                    مشخصات
                                                </th>
                                                <th>
                                                    وضعیت
                                                </th>
                                                <th>
                                                    جزئیات
                                                </th>
											</tr>
										</thead>
										<tbody>
                                        {% for order in orders %}

											<tr>
												<td><a href="{{ order.items.first.product.get_absolute_url }}"><img src="{{ order.items.first.product.images.first.file.url }}" width="50" height="60" alt="product picture"></a></td>
												<td>
													{{ order.created }}
												</td>
                                                <td><a href="{% url 'orders:order-detail' order.id %}">{{ order.items.first.product }}</a></td>
												<td>{{ order.items.first.price }}</td>
                                                <td>{{ order.items.first.quantity }}</td>
                                                <td>{{ order.items.first.weight }}</td>
                                                {% if order.paid %}
                                                <td><i class="fa fa-check text-success"></i></td>
                                                {% else %}
                                                <td><i class="fa fa-stop-circle text-danger"></i></td>
                                                {% endif %}
                                                <td><a href="{% url 'orders:order-detail' order.id %}" class="check-btn sqr-btn ">نمایش</a></td>
											</tr>
                                        {% endfor %}
										</tbody>
									</table>

								</div>
							</div>

						</div>
					</div>

				</div>

			</div>
		</div>
{% endblock %}
</html>

sabzshop/orders/templates/payment-tracking.html
<!DOCTYPE html>
<html dir="rtl">
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}تراکنش{% endblock %}

{% block content %}


		<div class="body">

			<div role="main" class="main">

				<section class="page-header page-header-modern page-header-background page-header-background-sm overlay overlay-color-primary overlay-show overlay-op-8 mb-5" style="background-image: url(img/page-header/page-header-elements.jpg);">
					<div class="container">
						<div class="row">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="mb-n2">تراکنش</h1>
							</div>
							<div class="col-md-12 align-self-center order-1">
								<ul class="breadcrumb breadcrumb-light d-block text-center">
								</ul>
							</div>
						</div>
					</div>
				</section>

				<div class="container py-2" style="margin-right: 15cm">
					<div class="row mb-5 pb-3">
						<div class="col-md-6 col-lg-4 mb-5 mb-lg-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="400">
                            {% if success %}
							<div class="card card-background-image-hover border-0 " style="background-color: darkgreen">
								<div class="card-body text-center p-5">
									<i class="fa fa-check-circle text-success"></i>
									<h4 class="card-title mt-2 mb-2 text-5 font-weight-bold">تراکنش موفق</h4>
                                    <p class="card-text">شماره پیگیری: {{ RefID }}</p>
                                    <p class="card-text">شماره سفارش: {{ order_id }}</p>
									<a href="{% url 'shop:index' %}" class="btn btn-primary btn-modern">خانه</a>
								</div>
							</div>
                            {% else %}
                            <div class="card card-background-image-hover border-0" style="background-color: #cd3333;">
								<div class="card-body text-center p-5">
									<i class="fa fa-minus-circle text-danger"></i>
									<h4 class="card-title mt-2 mb-2 text-5 font-weight-bold">تراکنش ناموفق</h4>
                                    <br>
									<a href="{% url 'shop:index' %}" class="btn btn-primary btn-modern">خانه</a>
								</div>
							</div>
                            {% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock %}
</html>

sabzshop/orders/templates/verify_code.html
<!DOCTYPE html>
<html dir="rtl">
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}تایید کد{% endblock %}

{% block content %}
		<div class="body">

			<div role="main" class="main">

				<section class="page-header page-header-modern page-header-background page-header-background-sm overlay overlay-color-primary overlay-show overlay-op-8 mb-5" style="background-image: url(img/page-header/page-header-elements.jpg);">
					<div class="container">
						<div class="row">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="mb-n2">بررسی کد تایید</h1>
							</div>
							<div class="col-md-12 align-self-center order-1">
								<ul class="breadcrumb breadcrumb-light d-block text-center">
{#									<li><a href="#">خانه</a></li>#}
{#									<li class="active">عناصر</li>#}
								</ul>
							</div>
						</div>
					</div>
				</section>

				<div class="container py-2">

					<div class="row">
						<div class="col">
                        <form  method="post">
							<section class="call-to-action featured featured-tertiary mb-5">
                            {% csrf_token %}
								<div class="mx-5">
									<div class="">

                                        <label>
                                            <input class="form-control blackboard-text"  type="text" name="code" placeholder="کد تایید را وارد کنید" style="margin-right: 3cm">
                                        </label>
                                        {% for message in messages %}
                                        <p class="mb-0" style="margin-right: 3cm"><strong class="font-weight-extra-bold text-success">{{ message }}</strong></p>
									    {% endfor %}
                                    </div>
								</div>
								<div class="" style="margin-right: 8cm">
									<div class="call-to-action-btn">
										<button type="submit" class="btn btn-modern text-2 btn-tertiary">کد تایید</button>
									</div>
								</div>

							</section>
                            </form>
						</div>
					</div>
				</div>
			</div>
 
		</div>
{% endblock %}
</html>